'use strict';
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('lab', {
  checkUpdate: () => ipcRenderer.invoke('update-check'),
  unhide: (dir) => ipcRenderer.invoke('unhide', dir),
  boot: () => ipcRenderer.invoke('boot'),
  setLang: (lang) => ipcRenderer.invoke('set-lang', lang),
  setTheme: (theme) => ipcRenderer.invoke('set-theme', theme),
  window: (action) => ipcRenderer.invoke('window', action),
  onWindowState: (handler) => ipcRenderer.on('window-state', (_event, maximized) => handler(maximized)),
  library: () => ipcRenderer.invoke('library'),
  scan: (dir) => ipcRenderer.invoke('scan', dir),
  history: () => ipcRenderer.invoke('history'),
  copyText: (text) => ipcRenderer.invoke('copy-text', text),
  saveDiagnostics: (dir, activity) => ipcRenderer.invoke('save-diagnostics', dir, activity),
  gameMenu: (dir, options) => ipcRenderer.invoke('game-menu', dir, options),
  settings: () => ipcRenderer.invoke('settings'),
  setDgVoodooVersion: (version) => ipcRenderer.invoke('set-dgvoodoo-version', version),
  setFeederVersion: (version) => ipcRenderer.invoke('set-feeder-version', version),
  setGroupGamesByStore: (enabled) => ipcRenderer.invoke('set-group-games-by-store', enabled),
  setCloseToTray: (enabled) => ipcRenderer.invoke('set-close-to-tray', enabled),
  driverNeuralFault: () => ipcRenderer.invoke('driver-neural-fault'),
  optiscalerBuilds: (dir) => ipcRenderer.invoke('optiscaler-builds', dir),
  setOptiscalerBuild: (dir, version) => ipcRenderer.invoke('set-optiscaler-build', dir, version),
  acknowledgeDriver: (names) => ipcRenderer.invoke('acknowledge-driver', names),
  setTrayLabels: (labels) => ipcRenderer.invoke('set-tray-labels', labels),
  setAutoScanDrives: (enabled) => ipcRenderer.invoke('set-auto-scan-drives', enabled),
  addFolder: () => ipcRenderer.invoke('add-folder'),
  removeFolder: (dir) => ipcRenderer.invoke('remove-folder', dir),
  excludeRoot: (dir) => ipcRenderer.invoke('exclude-root', dir),
  addGame: () => ipcRenderer.invoke('add-game'),
  addGameByPath: (dir) => ipcRenderer.invoke('add-game-path', dir),
  setPoster: (dir) => ipcRenderer.invoke('set-poster', dir),
  hide: (dir) => ipcRenderer.invoke('hide', dir),
  reset: () => ipcRenderer.invoke('reset'),
  open: (dir) => ipcRenderer.invoke('open', dir),
  openProject: (destination) => ipcRenderer.invoke('open-project', destination),
  setApiOverride: (dir, exePath, value) => ipcRenderer.invoke('set-api-override', dir, exePath, value),
  setDlssSource: (dir, value) => ipcRenderer.invoke('set-dlss-source', dir, value),
  artStatus: () => ipcRenderer.invoke('art-status'),
  artFetch: (dir, name, appid) => ipcRenderer.invoke('art-fetch', dir, name, appid),
  touch: (dir) => ipcRenderer.invoke('touch', dir),
  recents: () => ipcRenderer.invoke('recents'),
  details: (dir) => ipcRenderer.invoke('details', dir),
  install: (dir, exePath, route, api, addon, multiFrameGeneration, additionalEffects, dgVoodooVersion, mfgVersion, dlssSource, optiscalerVersion) => ipcRenderer.invoke('install', dir, exePath, route, api, addon, multiFrameGeneration, additionalEffects, dgVoodooVersion, mfgVersion, dlssSource, optiscalerVersion),
  applyGamePreset: (dir) => ipcRenderer.invoke('apply-game-preset', dir),
  addons: () => ipcRenderer.invoke('addons'),
  addonToggle: (file, on) => ipcRenderer.invoke('addon-toggle', file, on),
  addonPick: () => ipcRenderer.invoke('addon-pick'),
  addonSave: (entry) => ipcRenderer.invoke('addon-save', entry),
  addonRemove: (file) => ipcRenderer.invoke('addon-remove', file),
  dlssSources: () => ipcRenderer.invoke('dlss-sources'),
  dlssSourceAdd: () => ipcRenderer.invoke('dlss-source-add'),
  dlssSourceRemove: (dir) => ipcRenderer.invoke('dlss-source-remove', dir),
  restoreGame: (dir) => ipcRenderer.invoke('restore', dir),
  onJob: (handler) => ipcRenderer.on('job', (_e, event) => handler(event)),
  pathForFile: (file) => { try { return webUtils.getPathForFile(file); } catch { return null; } }
});
